### ISSUE TITLE
url_for has double id

### ISSUE THREAD

**Issue by winston** [choonkeat/active_waiter#16]
I can't figure this out yet, but for this line https://github.com/choonkeat/active_waiter/blob/master/app/views/active_waiter/jobs/_reload.html.erb#L2, the `url_for` is returning me URLs like:

```
/admin/active_waiter/ea1e2c95-570b-4444-aef8-35ff981b2488/ea1e2c95-570b-4444-aef8-35ff981b2488?download=1
```

instead of

```
/admin/active_waiter/ea1e2c95-570b-4444-aef8-35ff981b2488?download=1

```

Note the repeated ids.

When I tried to debug it and call `url_for` without any options.. it is still giving me double id.

Any ideas?

**Comment by choonkeat** [comment]
1. what is the `routes.rb` mount? e.g. can we peek at your current `rake routes | grep active_waiter`?
2. when `url_for` is returning the double id path, what is the current browser url ~ what are the values of `params`?

**Comment by winston** [comment]
Routes, mounted in the admin namespace:

```
namespace :admin do
    mount ActiveWaiter::Engine => '/active_waiter(/:id)'
end

```

Params:

```
[1] pry(#<#<Class:0x007fd2b93054d8>>)> params
=> {"download"=>"1", "id"=>"d11114d6-0398-414f-83ab-95a8e43c199e", "controller"=>"active_waiter/jobs", "action"=>"show"}
```

URL on first load is:

```
http://localhost:3000/admin/active_waiter/d11114d6-0398-414f-83ab-95a8e43c199e?download=1
```

Then because of `url_for` "bug", on auto refresh, it will become

```
http://localhost:3000/admin/active_waiter/d11114d6-0398-414f-83ab-95a8e43c199e/d11114d6-0398-414f-83ab-95a8e43c199e?download=1
```

**Comment by choonkeat** [comment]
seems like this should be the correct config

``` ruby
namespace :admin do
  mount ActiveWaiter::Engine => '/active_waiter'
end
```

**Comment by choonkeat** [comment]
ooh, scratch that. it breaks

``` ruby
redirect_to active_waiter_path(uid) #=> "/active_waiter" where is my uid?
```

**Comment by choonkeat** [comment]
After several trials (and unfortunately we can't really document this in the tests urls, params and request env is different there), to fix the double id occurrence, we need to change our instructions for the main app
1. mount engine without the optional path param
2. explicitly state `:id` key when using the named route, e.g. `active_waiter_path(id: uid, x: 1)` instead of the existing implicit `active_waiter_path(uid, x: 1)`

See diff at https://gist.github.com/choonkeat/926473e3dab14bf546a0/revisions

The downside is on the _first redirect from main app to engine_ the url would be `/active_waiter?id=aaaa` (notice `id` as explicit param). However, on subsequent reloads, it will become `/active_waiter/aaaa` (path param) and `/active_waiter/aaaa/aaaa` (duplicate) won't occur

WDYT?

**Comment by winston** [comment]
This works. I have also found that this can work too:

Modify route in gem:

```
ActiveWaiter::Engine.routes.draw do
  root to: 'jobs#show'
  get '/:id' => 'jobs#show', as: :job
end
```

Then mount routes like so in your app:

```
mount ActiveWaiter::Engine => '/active_waiter', as: :active_waiter
```

And use it like so in the controller:

```
redirect_to admin_active_waiter.job_path(uid, download: 1)
```

Note I have `admin_active_waiter` because it's wrapped in a name space.

So with this, then `first redirect from main app to engine the url would be` won't happen.

Ref: http://stackoverflow.com/questions/8029192/named-routes-in-mounted-rails-engine

Which do you prefer?

**Comment by choonkeat** [comment]
I prefer the one with lesser changes 🙈

**Comment by winston** [comment]
> I prefer the one with lesser changes

Ok. I'll go with https://github.com/choonkeat/active_waiter/issues/16#issuecomment-183680325 then.
